-- Update user_settings table
ALTER TABLE public.user_settings 
ADD COLUMN IF NOT EXISTS tax_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS setup_minutes NUMERIC DEFAULT 15,
ADD COLUMN IF NOT EXISTS post_processing_price_hour NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS layer_height NUMERIC DEFAULT 0.2,
ADD COLUMN IF NOT EXISTS nozzle_width NUMERIC DEFAULT 0.4,
ADD COLUMN IF NOT EXISTS walls INTEGER DEFAULT 3,
ADD COLUMN IF NOT EXISTS volumetric_rate NUMERIC DEFAULT 10,
ADD COLUMN IF NOT EXISTS time_calibration NUMERIC DEFAULT 1.0,
ADD COLUMN IF NOT EXISTS engine_version TEXT DEFAULT 'v1' CHECK (engine_version IN ('v1', 'v2'));

-- Update quotes table
ALTER TABLE public.quotes 
ADD COLUMN IF NOT EXISTS quantity INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS tax_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_value NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cost_support NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cost_post NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cost_setup NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'manual',
ADD COLUMN IF NOT EXISTS stl_volume_cm3 NUMERIC,
ADD COLUMN IF NOT EXISTS stl_area_cm2 NUMERIC,
ADD COLUMN IF NOT EXISTS dim_x NUMERIC,
ADD COLUMN IF NOT EXISTS dim_y NUMERIC,
ADD COLUMN IF NOT EXISTS dim_z NUMERIC,
ADD COLUMN IF NOT EXISTS infill_pct NUMERIC,
ADD COLUMN IF NOT EXISTS engine_version TEXT DEFAULT 'v1';
